# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 00:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20171007_0007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='img_url',
            new_name='image',
        ),
    ]
